name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['6', '8', '10', '12', '14', '16']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run coverage
      - uses: coverallsapp/github-action@master
        if: ${{ success() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
